export default {
  cars: [
    {
      id: 1,
      email: 'amadi@gmail.com',
      createdOn: '2019-07-19',
      manufacturer: 'toyota',
      model: 'Camry',
      price: 700000.00,
      state: 'used',
      status: 'available',
      bodyType: 'car',
      imageUrl: 'https://unsplash.com/automobiles?camry',
    },
    {
      id: 2,
      email: 'dualipa@gmail.com',
      createdOn: '2019-07-20',
      manufacturer: 'lexus',
      model: 'RX500',
      price: 1500000.00,
      state: 'new',
      status: 'available',
      bodyType: 'car',
      imageUrl: 'https://unsplash.com/automobiles?lexus',
    },
    {
      id: 3,
      email: 'noone@aol.com',
      createdOn: '2019-08-01',
      manufacturer: 'toyota',
      model: 'Camry',
      price: 900000.00,
      state: 'new',
      status: 'sold',
      bodyType: 'car',
      imageUrl: 'https://unsplash.com/automobiles?camry',
    },
    {
      id: 4,
      email: 'jonsnow@gmail.com',
      state: 'new',
      status: 'sold',
      price: 9500000.00,
      manufacturer: 'Ford',
      model: '2019 Ranger',
      bodyType: 'truck',
      imageUrl: 'someurl',
      createdOn: '19-03-2019',
    },
    {
      id: 5,
      email: 'zayn@gmail.com',
      createdOn: '2019-08-14',
      manufacturer: 'toyota',
      model: 'hiace',
      price: 20000000.00,
      state: 'new',
      status: 'available',
      bodyType: 'van',
      imageUrl: 'https://unsplash.com/automobiles?camry',
    },
    {
      id: 6,
      email: 'amadi@gmail.com',
      createdOn: '2019-08-14',
      manufacturer: 'toyota',
      model: 'tundra',
      price: 20000000.00,
      state: 'new',
      status: 'available',
      bodyType: 'truck',
      imageUrl: 'https://unsplash.com/automobiles?camry',
    },
    {
      id: 7,
      email: 'noone@aol.com',
      createdOn: '2019-08-14',
      manufacturer: 'mercedes',
      model: 'ml350',
      price: 20000000.00,
      state: 'new',
      status: 'available',
      bodyType: 's.u.v',
      imageUrl: 'https://unsplash.com/automobiles?camry',
    },
  ],
};
